name: IMiniMessage
main: me.zortex.iminimessage.IMiniMessage
version: ${version}
api-version: 1.19
authors: [ghost2020y]
description: Global MiniMessage interceptor using PacketEvents
depend: [packetevents]
permissions:
  iminimessage.use:
    description: Allows the player to use MiniMessage tags in chat.
    default: op